#!/bin/bash
# 2X as 3X

trap "/usr/bin/killall -q -u $USER Yahtzee 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stdout=stdout.out -stderr=/dev/null ./Yahtzee -mystery -scoring < /c/cs427/hw6/Tests/t019.in
cat stdout.out | /usr/bin/head -n 17
