#!/bin/bash
# One 1

trap "/usr/bin/killall -q -u $USER Yahtzee 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stdout=stdout.out -stderr=/dev/null ./Yahtzee -regular -scoring < /c/cs427/hw5/Tests/t002.in
cat stdout.out | /usr/bin/head -n 15
